import React, { useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { LinkParseError, parseLinkUrl, parseManualSecret } from '../src/lib/link-url';
import { useVaultSession } from '../src/lib/vault-session';
import { Button, ErrorNote, FieldLabel, colors } from '../src/ui';

/**
 * Device linking (M6-1): scan the QR the desktop GUI renders
 * (northkeep://link/v1?ds=...), or paste the code manually. The secret goes
 * straight into SecureStore; it is never displayed back and never leaves the
 * device.
 *
 * NEEDS ON-DEVICE VALIDATION: camera permission flow, QR scan callback
 * cadence (onBarcodeScanned fires repeatedly; guarded by a ref), and the
 * end-to-end scan of a QR generated by the desktop GUI.
 */
export default function DeviceLink() {
  const session = useVaultSession();
  const [permission, requestPermission] = useCameraPermissions();
  const [error, setError] = useState<string | null>(null);
  const [manual, setManual] = useState('');
  const [busy, setBusy] = useState(false);
  const handledRef = useRef(false);

  async function completeLink(deviceSecretHex: string) {
    setBusy(true);
    try {
      await session.linkDevice(deviceSecretHex);
      router.replace('/unlock');
    } finally {
      setBusy(false);
    }
  }

  function onScanned(data: string) {
    if (handledRef.current) return;
    try {
      const hex = parseLinkUrl(data);
      handledRef.current = true; // only stop scanning once a code parses
      setError(null);
      void completeLink(hex);
    } catch (err) {
      setError(err instanceof LinkParseError ? err.message : 'Could not read that code.');
    }
  }

  function onManualSubmit() {
    try {
      const hex = parseManualSecret(manual);
      setError(null);
      void completeLink(hex);
    } catch (err) {
      setError(err instanceof LinkParseError ? err.message : 'Could not read that code.');
    }
  }

  return (
    <KeyboardAvoidingView
      style={styles.screen}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
        <Text style={styles.body}>
          On your Mac, open NorthKeep and choose Link mobile device, then point this camera at the
          code.
        </Text>

        {permission?.granted ? (
          <View style={styles.cameraBox}>
            <CameraView
              style={styles.camera}
              facing="back"
              barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
              onBarcodeScanned={({ data }) => onScanned(data)}
            />
          </View>
        ) : (
          <View style={styles.permissionBox}>
            <Text style={styles.body}>
              NorthKeep needs the camera only while you scan the link code.
            </Text>
            <Button
              title="Allow camera"
              onPress={() => void requestPermission()}
              disabled={permission !== null && !permission.canAskAgain}
            />
            {permission !== null && !permission.canAskAgain ? (
              <Text style={styles.footnote}>
                Camera access is off for NorthKeep. Enable it in system Settings, or paste the code
                below instead.
              </Text>
            ) : null}
          </View>
        )}

        <ErrorNote message={error} />

        <FieldLabel>Or paste the code</FieldLabel>
        <Text style={styles.footnote}>
          Paste the full northkeep:// link, or the contents of the device.secret file from your
          Mac.
        </Text>
        <TextInput
          style={styles.input}
          value={manual}
          onChangeText={setManual}
          autoCapitalize="none"
          autoCorrect={false}
          placeholder="northkeep://link/v1?ds=..."
          placeholderTextColor={colors.muted}
          multiline
        />
        <Button title="Link this phone" onPress={onManualSubmit} busy={busy} disabled={manual.trim().length === 0} />
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20 },
  body: { color: colors.text, fontSize: 15, lineHeight: 22, marginBottom: 16 },
  cameraBox: {
    borderRadius: 14,
    overflow: 'hidden',
    aspectRatio: 1,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  camera: { flex: 1 },
  permissionBox: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 20,
    marginBottom: 16,
  },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.text,
    padding: 12,
    minHeight: 72,
    marginBottom: 12,
    fontSize: 14,
  },
  footnote: { color: colors.muted, fontSize: 13, lineHeight: 19, marginBottom: 8 },
});
