export { timeoutSignal, withTimeout } from './abort.js';
export {
  AutoSync,
  AUTO_PULL_BACKUP_SUFFIX,
  DIVERGED_MESSAGE,
  syncAge,
  type AutoSyncClock,
  type AutoSyncEvent,
  type AutoSyncOptions,
  type AutoSyncPhase,
  type AutoSyncStatus,
} from './auto.js';
export { deriveConnectorToken, deriveSyncCreds, tokenHash, type SyncCreds } from './creds.js';
export {
  assertSyncUrl,
  loadSyncConfig,
  saveSyncConfig,
  setSyncServer,
  syncConfigPath,
  type SyncConfig,
} from './config.js';
export {
  MAX_BLOB_BYTES,
  computeDropReport,
  confirmPull,
  previewPull,
  pullWouldDrop,
  PullWouldDropError,
  RemoteChangedError,
  type PullDropReport,
  type PullPreview,
  pullVault,
  pushVault,
  syncState,
  subscriptionStatus,
  checkoutUrl,
  portalUrl,
  SubscriptionRequiredError,
  LocalChangedError,
  SyncBusyError,
  isAutoSyncVault,
  type PullResult,
  type PushResult,
  type RemoteStatus,
  type SyncState,
  type SubscriptionStatus,
} from './client.js';
export {
  assertConnectorUrl,
  connectorConfigPath,
  connectorPairedAt,
  connectorPaired,
  connectorLastPushedAt,
  connectorAutoPushEnabled,
  connectorPushFingerprint,
  setConnectorAutoPush,
  markConnectorPushed,
  foldSidecarScopesIntoVault,
  markConnectorPaired,
  loadConnectorConfig,
  saveConnectorConfig,
  setConnectorServer,
  type ConnectorConfig,
} from './connector-config.js';
export {
  applyDownSync,
  BASE_NEW,
  ConnectorStalePushError,
  ConnectorTombstoneError,
  discardPending,
  fetchEntitlement,
  fetchPending,
  getConnectorManifest,
  getManifest,
  holdMessage,
  keptCloudVersionTitle,
  planDownSync,
  planNeedsConfirmation,
  pushSharedScopes,
  resolveConflict,
  startPairing,
  unshareScope,
  STALE_PUSH_MESSAGE,
  type ConflictChoice,
  type ConflictReason,
  type DownSyncConflict,
  type DownSyncPlan,
  type DownSyncResult,
  type ManifestEntry,
  type PendingRow,
  type PendingSnapshot,
  type PlannedAddition,
  type PlannedForget,
  type PlannedReplacement,
  type PushEntry,
  type PushSharedResult,
  type ResolveResult,
  type VaultStamp,
  UNSHARE_FAILED_MESSAGE,
  UNSHARE_LOCAL_SAVE_FAILED_MESSAGE,
  LAPSED_UNSHARE_HINT,
} from './connector-client.js';
export {
  CONNECTOR_AUTO_PUSH_MESSAGES,
  ConnectorAutoPush,
  type ConnectorAutoPushEvent,
  type ConnectorAutoPushOptions,
  type ConnectorAutoPushPhase,
  type ConnectorAutoPushReason,
  type ConnectorAutoPushStatus,
} from './connector-auto.js';
export {
  assertDeviceCanPush,
  ConnectorPushBlockedError,
  manualConnectorPush,
  manualVaultStamp,
  pushSnapshot,
  snapshotSharedScopes,
  vaultServerHash,
  type PushBlockedReason,
  type SharedSnapshot,
} from './connector-push.js';
