// Regenerates src/data.gen.ts from data/*.txt (ADR 0022 name lists).
// The generated module is CHECKED IN so tests and fresh clones work without a
// build step, and so Metro (mobile) can bundle the lists without node:fs.
// Run after refreshing the .txt sources: node scripts/gen-data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(here, '..', 'data');
const out = path.join(here, '..', 'src', 'data.gen.ts');

const read = (f) => fs.readFileSync(path.join(dataDir, f), 'utf8').trimEnd();

const banner = `// GENERATED by scripts/gen-data.mjs from data/*.txt — do not edit by hand.
// Bundled as a plain module (not fs-loaded) so the SAME code path works under
// Node (desktop/CLI) and Metro/Hermes (mobile), which cannot read package data
// files at runtime. english is in FREQUENCY ORDER (rank matters — ADR 0022).
`;

const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

fs.writeFileSync(
  out,
  banner +
    `export const FIRSTNAMES_TXT: string = ${lit(read('firstnames.txt'))};\n\n` +
    `export const SURNAMES_TXT: string = ${lit(read('surnames.txt'))};\n\n` +
    `export const ENGLISH_TXT: string = ${lit(read('english.txt'))};\n`,
);
console.log('wrote', out, fs.statSync(out).size, 'bytes');
